package com.lfboo.demo.dao.mapper;

import com.lfboo.demo.dao.entity.MUser;
import java.util.List;

public interface MUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    int insert(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    MUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    List<MUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    int updateByPrimaryKey(MUser record);
}