package com.lfboo.demo.dao.entity;

public class MUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.id
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.name
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.address
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.create_time
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.update_time
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.deleted
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.id
     *
     * @return the value of m_user.id
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.id
     *
     * @param id the value for m_user.id
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.name
     *
     * @return the value of m_user.name
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.name
     *
     * @param name the value for m_user.name
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.address
     *
     * @return the value of m_user.address
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.address
     *
     * @param address the value for m_user.address
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.create_time
     *
     * @return the value of m_user.create_time
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.create_time
     *
     * @param createTime the value for m_user.create_time
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.update_time
     *
     * @return the value of m_user.update_time
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.update_time
     *
     * @param updateTime the value for m_user.update_time
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.deleted
     *
     * @return the value of m_user.deleted
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.deleted
     *
     * @param deleted the value for m_user.deleted
     *
     * @mbg.generated Sun Aug 12 21:32:44 CST 2018
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}